python main.py --dataset=cora --n_layers=2 --split=1 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=2 --split=2 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=2 --split=3 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=2 --split=4 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=2 --split=5 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=2 --split=6 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=2 --split=7 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=2 --split=8 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=2 --split=9 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=2 --split=10 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=4 --split=1 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=4 --split=2 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=4 --split=3 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=4 --split=4 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=4 --split=5 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=4 --split=6 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=4 --split=7 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=4 --split=8 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=4 --split=9 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=4 --split=10 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=8 --split=1 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=8 --split=2 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=8 --split=3 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=8 --split=4 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=8 --split=5 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=8 --split=6 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=8 --split=7 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=8 --split=8 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=8 --split=9 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=8 --split=10 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=16 --split=1 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=16 --split=2 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=16 --split=3 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=16 --split=4 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=16 --split=5 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=16 --split=6 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=16 --split=7 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=16 --split=8 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=16 --split=9 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=16 --split=10 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=32 --split=1 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=32 --split=2 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=32 --split=3 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=32 --split=4 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=32 --split=5 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=32 --split=6 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=32 --split=7 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=32 --split=8 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=32 --split=9 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=32 --split=10 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=64 --split=1 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=64 --split=2 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=64 --split=3 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=64 --split=4 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=64 --split=5 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=64 --split=6 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=64 --split=7 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=64 --split=8 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=64 --split=9 --data=cocitation --n-runs 10
python main.py --dataset=cora --n_layers=64 --split=10 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=2 --split=1 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=2 --split=2 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=2 --split=3 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=2 --split=4 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=2 --split=5 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=2 --split=6 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=2 --split=7 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=2 --split=8 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=2 --split=9 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=2 --split=10 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=4 --split=1 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=4 --split=2 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=4 --split=3 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=4 --split=4 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=4 --split=5 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=4 --split=6 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=4 --split=7 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=4 --split=8 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=4 --split=9 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=4 --split=10 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=8 --split=1 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=8 --split=2 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=8 --split=3 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=8 --split=4 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=8 --split=5 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=8 --split=6 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=8 --split=7 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=8 --split=8 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=8 --split=9 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=8 --split=10 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=16 --split=1 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=16 --split=2 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=16 --split=3 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=16 --split=4 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=16 --split=5 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=16 --split=6 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=16 --split=7 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=16 --split=8 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=16 --split=9 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=16 --split=10 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=32 --split=1 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=32 --split=2 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=32 --split=3 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=32 --split=4 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=32 --split=5 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=32 --split=6 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=32 --split=7 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=32 --split=8 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=32 --split=9 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=32 --split=10 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=64 --split=1 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=64 --split=2 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=64 --split=3 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=64 --split=4 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=64 --split=5 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=64 --split=6 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=64 --split=7 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=64 --split=8 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=64 --split=9 --data=cocitation --n-runs 10
python main.py --dataset=pubmed --n_layers=64 --split=10 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=2 --split=1 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=2 --split=2 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=2 --split=3 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=2 --split=4 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=2 --split=5 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=2 --split=6 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=2 --split=7 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=2 --split=8 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=2 --split=9 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=2 --split=10 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=4 --split=1 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=4 --split=2 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=4 --split=3 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=4 --split=4 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=4 --split=5 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=4 --split=6 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=4 --split=7 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=4 --split=8 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=4 --split=9 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=4 --split=10 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=8 --split=1 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=8 --split=2 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=8 --split=3 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=8 --split=4 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=8 --split=5 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=8 --split=6 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=8 --split=7 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=8 --split=8 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=8 --split=9 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=8 --split=10 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=16 --split=1 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=16 --split=2 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=16 --split=3 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=16 --split=4 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=16 --split=5 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=16 --split=6 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=16 --split=7 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=16 --split=8 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=16 --split=9 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=16 --split=10 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=32 --split=1 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=32 --split=2 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=32 --split=3 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=32 --split=4 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=32 --split=5 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=32 --split=6 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=32 --split=7 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=32 --split=8 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=32 --split=9 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=32 --split=10 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=64 --split=1 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=64 --split=2 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=64 --split=3 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=64 --split=4 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=64 --split=5 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=64 --split=6 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=64 --split=7 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=64 --split=8 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=64 --split=9 --data=cocitation --n-runs 10
python main.py --dataset=citeseer --n_layers=64 --split=10 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=2 --split=1 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=2 --split=2 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=2 --split=3 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=2 --split=4 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=2 --split=5 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=2 --split=6 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=2 --split=7 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=2 --split=8 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=2 --split=9 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=2 --split=10 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=4 --split=1 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=4 --split=2 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=4 --split=3 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=4 --split=4 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=4 --split=5 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=4 --split=6 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=4 --split=7 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=4 --split=8 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=4 --split=9 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=4 --split=10 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=8 --split=1 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=8 --split=2 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=8 --split=3 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=8 --split=4 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=8 --split=5 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=8 --split=6 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=8 --split=7 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=8 --split=8 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=8 --split=9 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=8 --split=10 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=16 --split=1 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=16 --split=2 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=16 --split=3 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=16 --split=4 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=16 --split=5 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=16 --split=6 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=16 --split=7 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=16 --split=8 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=16 --split=9 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=16 --split=10 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=32 --split=1 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=32 --split=2 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=32 --split=3 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=32 --split=4 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=32 --split=5 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=32 --split=6 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=32 --split=7 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=32 --split=8 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=32 --split=9 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=32 --split=10 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=64 --split=1 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=64 --split=2 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=64 --split=3 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=64 --split=4 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=64 --split=5 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=64 --split=6 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=64 --split=7 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=64 --split=8 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=64 --split=9 --data=cocitation --n-runs 10
python main.py --dataset=NTU2012 --n_layers=64 --split=10 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=2 --split=1 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=2 --split=2 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=2 --split=3 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=2 --split=4 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=2 --split=5 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=2 --split=6 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=2 --split=7 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=2 --split=8 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=2 --split=9 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=2 --split=10 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=4 --split=1 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=4 --split=2 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=4 --split=3 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=4 --split=4 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=4 --split=5 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=4 --split=6 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=4 --split=7 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=4 --split=8 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=4 --split=9 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=4 --split=10 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=8 --split=1 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=8 --split=2 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=8 --split=3 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=8 --split=4 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=8 --split=5 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=8 --split=6 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=8 --split=7 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=8 --split=8 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=8 --split=9 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=8 --split=10 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=16 --split=1 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=16 --split=2 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=16 --split=3 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=16 --split=4 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=16 --split=5 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=16 --split=6 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=16 --split=7 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=16 --split=8 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=16 --split=9 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=16 --split=10 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=32 --split=1 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=32 --split=2 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=32 --split=3 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=32 --split=4 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=32 --split=5 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=32 --split=6 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=32 --split=7 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=32 --split=8 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=32 --split=9 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=32 --split=10 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=64 --split=1 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=64 --split=2 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=64 --split=3 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=64 --split=4 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=64 --split=5 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=64 --split=6 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=64 --split=7 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=64 --split=8 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=64 --split=9 --data=cocitation --n-runs 10
python main.py --dataset=ModelNet40 --n_layers=64 --split=10 --data=cocitation --n-runs 10
